window.TL = {
  "fps": 30,
  "bpm": 120,
  "voice": "am_fenrir",
  "_comment": "Animation cues (scenes, cuts, sfx, breakdown) are in DESIGN time. 'segments' maps each design span onto its real length so scenes stretch to fit the voiceover; every real boundary sits on a beat. 'duration' and narration start/end are REAL time (narration times are written by voice.py).",
  "segments": [
    { "id": "hook",    "design": [0.0, 2.0],      "real": 2.0 },
    { "id": "intro",   "design": [2.0, 4.0],      "real": 2.5 },
    { "id": "build",   "design": [4.0, 7.0],      "real": 4.0 },
    { "id": "ms",      "design": [7.0, 10.5],     "real": 5.0 },
    { "id": "cf",      "design": [10.5, 13.0],    "real": 3.0 },
    { "id": "proof1",  "design": [13.0, 14.333],  "real": 2.0 },
    { "id": "proof2",  "design": [14.333, 15.667],"real": 2.5 },
    { "id": "proof3",  "design": [15.667, 17.0], "real": 2.0 },
    { "id": "stack",   "design": [17.0, 19.0],    "real": 3.5 },
    { "id": "process", "design": [19.0, 22.0],    "real": 3.0 },
    { "id": "cta",     "design": [22.0, 25.5],    "real": 5.5 },
    { "id": "loop",    "design": [25.5, 26.0],    "real": 1.0 }
  ],
  "duration": 36.0,
  "scenes": [
    { "id": "hook",    "start": 0.0,  "end": 2.0  },
    { "id": "intro",   "start": 2.0,  "end": 4.0  },
    { "id": "build",   "start": 4.0,  "end": 7.0  },
    { "id": "ms",      "start": 7.0,  "end": 10.5 },
    { "id": "cf",      "start": 10.5, "end": 13.0 },
    { "id": "proof",   "start": 13.0, "end": 17.0 },
    { "id": "stack",   "start": 17.0, "end": 19.0 },
    { "id": "process", "start": 19.0, "end": 22.0 },
    { "id": "cta",     "start": 22.0, "end": 25.5 },
    { "id": "loop",    "start": 25.5, "end": 26.0 }
  ],
  "cuts": [2.0, 4.0, 7.0, 10.5, 13.0, 14.333, 15.667, 17.0, 19.0, 22.0, 25.5],
  "narration": [
    { "seg": 0,  "start": 0.05, "end": 1.87, "text": "Six weeks. Idea to live product.", "say": "Six weeks. Idea to [live](/lˈaɪv/) product.", "speed": 1.1 },
    { "seg": 1,  "start": 2.1, "end": 4.38, "text": "Hi, I'm Rhydham. Full-stack engineer and founder.", "say": "Hi, I'm Rhythm. Full-stack engineer, and founder.", "speed": 1.15 },
    { "seg": 2,  "start": 4.6, "end": 8.12, "text": "I build the whole thing: frontend, backend, database, SEO. Shipped.", "say": "I build the whole thing: front end, back end, database, S E O. Shipped.", "speed": 1.2 },
    { "seg": 3,  "start": 8.6, "end": 13.39, "text": "My startup MentalSaathi hit 1,500 visitors in month one. Zero ad spend.", "say": "My startup, Mental Saathee, hit fifteen hundred visitors in month one. Zero ad spend.", "speed": 1.2 },
    { "seg": 4,  "start": 13.6, "end": 16.31, "text": "CollabFluenz: built for a founder. Live in production.", "say": "Collab Fluence: built for a founder. [Live](/lˈaɪv/) in production.", "speed": 1.15 },
    { "seg": 5,  "start": 16.55, "end": 18.42, "text": "Zero-downtime database migration.", "say": "Zero-downtime database migration.", "speed": 1.15 },
    { "seg": 6,  "start": 18.6, "end": 20.88, "text": "91% accurate sign-language AI.", "say": "Ninety-one percent accurate sign-language A I.", "speed": 1.15 },
    { "seg": 7,  "start": 21.1, "end": 22.51, "text": "My own open-source framework.", "say": "My own open-source framework.", "speed": 1.1 },
    { "seg": 8,  "start": 23.03, "end": 26.42, "text": "Next.js, FastAPI, Postgres. One dev, full stack.", "say": "Next J S, Fast A P I, Postgres. One dev, full stack.", "speed": 1.15 },
    { "seg": 9,  "start": 26.6, "end": 29.01, "text": "Weekly builds you can click. Not status updates.", "say": "Weekly builds you can click. Not status updates.", "speed": 1.1 },
    { "seg": 10, "start": 29.6, "end": 32.83, "text": "Got something that needs building? Comment BUILD and I'll DM you.", "say": "Got something that needs building? Comment, build, and I'll D M you.", "speed": 1.1 },
    { "seg": 11, "start": 34.99, "end": 35.86, "text": "Your idea, live in...", "say": "Your idea, [live](/lˈaɪv/) in", "speed": 1.1 }
  ],
  "sfx": [
    { "t": 0.0,   "type": "impact" },
    { "t": 0.3,   "type": "impact" },
    { "t": 1.0,   "type": "stamp" },
    { "t": 3.1,   "type": "pop" },
    { "t": 4.25,  "type": "typing", "dur": 0.6, "chars": 27 },
    { "t": 4.95,  "type": "pop" },
    { "t": 5.25,  "type": "pop" },
    { "t": 5.55,  "type": "pop" },
    { "t": 5.85,  "type": "pop" },
    { "t": 6.25,  "type": "chime" },
    { "t": 8.0,   "type": "pop" },
    { "t": 8.5,   "type": "ticks", "dur": 0.8 },
    { "t": 9.0,   "type": "pop" },
    { "t": 11.2,  "type": "pop" },
    { "t": 11.6,  "type": "pop" },
    { "t": 12.0,  "type": "chime" },
    { "t": 13.0,  "type": "impact" },
    { "t": 14.333,"type": "impact" },
    { "t": 15.667,"type": "impact" },
    { "t": 15.9,  "type": "typing", "dur": 0.5, "chars": 24 },
    { "t": 17.15, "type": "slam" }, { "t": 17.35, "type": "slam" },
    { "t": 17.55, "type": "slam" }, { "t": 17.75, "type": "slam" },
    { "t": 17.95, "type": "slam" }, { "t": 18.15, "type": "slam" },
    { "t": 18.35, "type": "slam" }, { "t": 18.55, "type": "slam" },
    { "t": 19.4,  "type": "tick" }, { "t": 19.85, "type": "tick" },
    { "t": 20.3,  "type": "tick" }, { "t": 20.75, "type": "tick" },
    { "t": 21.2,  "type": "tick" },
    { "t": 20.5,  "type": "riser", "dur": 1.5 },
    { "t": 22.0,  "type": "impact" },
    { "t": 23.1,  "type": "stamp" },
    { "t": 23.6,  "type": "chime" }
  ],
  "breakdown": [21.5, 22.0]
};
