window.TL = {
  "fps": 30,
  "duration": 26.0,
  "bpm": 120,
  "scenes": [
    { "id": "hook",    "start": 0.0,  "end": 2.0  },
    { "id": "intro",   "start": 2.0,  "end": 4.0  },
    { "id": "build",   "start": 4.0,  "end": 7.0  },
    { "id": "ms",      "start": 7.0,  "end": 10.5 },
    { "id": "cf",      "start": 10.5, "end": 13.0 },
    { "id": "proof",   "start": 13.0, "end": 17.0 },
    { "id": "stack",   "start": 17.0, "end": 19.0 },
    { "id": "process", "start": 19.0, "end": 22.0 },
    { "id": "cta",     "start": 22.0, "end": 25.5 },
    { "id": "loop",    "start": 25.5, "end": 26.0 }
  ],
  "cuts": [2.0, 4.0, 7.0, 10.5, 13.0, 14.333, 15.667, 17.0, 19.0, 22.0, 25.5],
  "narration": [
    { "start": 0.05,  "end": 1.9,   "text": "Six weeks. Idea to live product." },
    { "start": 2.1,   "end": 3.9,   "text": "Hi, I'm Rhydham. Full-stack engineer and founder." },
    { "start": 4.1,   "end": 6.9,   "text": "I build the whole thing: frontend, backend, database, SEO. Shipped." },
    { "start": 7.1,   "end": 10.35, "text": "My startup MentalSaathi hit 1,500 visitors in month one. Zero ad spend." },
    { "start": 10.6,  "end": 12.9,  "text": "CollabFluenz: built for a founder. Live in production." },
    { "start": 13.1,  "end": 14.25, "text": "Zero-downtime database migration." },
    { "start": 14.4,  "end": 15.6,  "text": "91% accurate sign-language AI." },
    { "start": 15.75, "end": 16.9,  "text": "My own open-source framework." },
    { "start": 17.1,  "end": 18.9,  "text": "Next.js, FastAPI, Postgres. One dev, full stack." },
    { "start": 19.1,  "end": 21.4,  "text": "Weekly builds you can click. Not status updates." },
    { "start": 22.1,  "end": 25.3,  "text": "Got something that needs building? Comment BUILD and I'll DM you." },
    { "start": 25.5,  "end": 25.98, "text": "Your idea, live in..." }
  ],
  "sfx": [
    { "t": 0.0,   "type": "impact" },
    { "t": 0.3,   "type": "impact" },
    { "t": 1.0,   "type": "stamp" },
    { "t": 3.1,   "type": "pop" },
    { "t": 4.25,  "type": "typing", "dur": 0.6, "chars": 27 },
    { "t": 4.95,  "type": "pop" },
    { "t": 5.25,  "type": "pop" },
    { "t": 5.55,  "type": "pop" },
    { "t": 5.85,  "type": "pop" },
    { "t": 6.25,  "type": "chime" },
    { "t": 8.0,   "type": "pop" },
    { "t": 8.5,   "type": "ticks", "dur": 0.8 },
    { "t": 9.0,   "type": "pop" },
    { "t": 11.2,  "type": "pop" },
    { "t": 11.6,  "type": "pop" },
    { "t": 12.0,  "type": "chime" },
    { "t": 13.0,  "type": "impact" },
    { "t": 14.333,"type": "impact" },
    { "t": 15.667,"type": "impact" },
    { "t": 15.9,  "type": "typing", "dur": 0.5, "chars": 24 },
    { "t": 17.15, "type": "slam" }, { "t": 17.35, "type": "slam" },
    { "t": 17.55, "type": "slam" }, { "t": 17.75, "type": "slam" },
    { "t": 17.95, "type": "slam" }, { "t": 18.15, "type": "slam" },
    { "t": 18.35, "type": "slam" }, { "t": 18.55, "type": "slam" },
    { "t": 19.4,  "type": "tick" }, { "t": 19.85, "type": "tick" },
    { "t": 20.3,  "type": "tick" }, { "t": 20.75, "type": "tick" },
    { "t": 21.2,  "type": "tick" },
    { "t": 20.5,  "type": "riser", "dur": 1.5 },
    { "t": 22.0,  "type": "impact" },
    { "t": 23.1,  "type": "stamp" },
    { "t": 23.6,  "type": "chime" }
  ],
  "breakdown": [21.5, 22.0]
};
